/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AdminImportMemberPersonalDataRequest } from "./AdminImportMemberPersonalDataRequest";
import {
  AdminImportMemberPersonalDataRequestFromJSON,
  AdminImportMemberPersonalDataRequestToJSON,
} from "./AdminImportMemberPersonalDataRequest";

/**
 * Admin-only DB import of a single Member with subscriptions and pickup
 * location. Mirrors BestellWizardConfirmOrderRequestSerializer but with the
 * PersonalData email/phone validators disabled and all coop (Genossenschaft)
 * logic stripped — this Tapir instance runs as a Verein (LEGAL_STATUS_ASSOCIATION).
 * @export
 * @interface AdminImportMemberRequestRequest
 */
export interface AdminImportMemberRequestRequest {
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof AdminImportMemberRequestRequest
   */
  shoppingCartOrder: { [key: string]: number };
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof AdminImportMemberRequestRequest
   */
  shoppingCartWaitingList: { [key: string]: number };
  /**
   *
   * @type {AdminImportMemberPersonalDataRequest}
   * @memberof AdminImportMemberRequestRequest
   */
  personalData: AdminImportMemberPersonalDataRequest;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  sepaAllowed: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  contractAccepted: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  statuteAccepted: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof AdminImportMemberRequestRequest
   */
  pickupLocationIds: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  studentStatusEnabled: boolean;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberRequestRequest
   */
  paymentRhythm: string;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  becomeMemberNow: boolean | null;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  privacyPolicyRead: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  cancellationPolicyRead: boolean;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberRequestRequest
   */
  growingPeriodId: string;
  /**
   *
   * @type {number}
   * @memberof AdminImportMemberRequestRequest
   */
  solidarityContribution: number;
  /**
   *
   * @type {Array<string>}
   * @memberof AdminImportMemberRequestRequest
   */
  distributionChannels: Array<string>;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberRequestRequest
   */
  feedback?: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberRequestRequest
   */
  associationMembershipTypeId?: string;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberRequestRequest
   */
  keycloakLookup?: boolean;
  /**
   *
   * @type {Date}
   * @memberof AdminImportMemberRequestRequest
   */
  dateJoined?: Date | null;
  /**
   *
   * @type {Date}
   * @memberof AdminImportMemberRequestRequest
   */
  privacyConsent?: Date | null;
  /**
   *
   * @type {number}
   * @memberof AdminImportMemberRequestRequest
   */
  memberNo?: number | null;
}

/**
 * Check if a given object implements the AdminImportMemberRequestRequest interface.
 */
export function instanceOfAdminImportMemberRequestRequest(
  value: object,
): value is AdminImportMemberRequestRequest {
  if (
    !("shoppingCartOrder" in value) ||
    value["shoppingCartOrder"] === undefined
  )
    return false;
  if (
    !("shoppingCartWaitingList" in value) ||
    value["shoppingCartWaitingList"] === undefined
  )
    return false;
  if (!("personalData" in value) || value["personalData"] === undefined)
    return false;
  if (!("sepaAllowed" in value) || value["sepaAllowed"] === undefined)
    return false;
  if (!("contractAccepted" in value) || value["contractAccepted"] === undefined)
    return false;
  if (!("statuteAccepted" in value) || value["statuteAccepted"] === undefined)
    return false;
  if (
    !("pickupLocationIds" in value) ||
    value["pickupLocationIds"] === undefined
  )
    return false;
  if (
    !("studentStatusEnabled" in value) ||
    value["studentStatusEnabled"] === undefined
  )
    return false;
  if (!("paymentRhythm" in value) || value["paymentRhythm"] === undefined)
    return false;
  if (!("becomeMemberNow" in value) || value["becomeMemberNow"] === undefined)
    return false;
  if (
    !("privacyPolicyRead" in value) ||
    value["privacyPolicyRead"] === undefined
  )
    return false;
  if (
    !("cancellationPolicyRead" in value) ||
    value["cancellationPolicyRead"] === undefined
  )
    return false;
  if (!("growingPeriodId" in value) || value["growingPeriodId"] === undefined)
    return false;
  if (
    !("solidarityContribution" in value) ||
    value["solidarityContribution"] === undefined
  )
    return false;
  if (
    !("distributionChannels" in value) ||
    value["distributionChannels"] === undefined
  )
    return false;
  return true;
}

export function AdminImportMemberRequestRequestFromJSON(
  json: any,
): AdminImportMemberRequestRequest {
  return AdminImportMemberRequestRequestFromJSONTyped(json, false);
}

export function AdminImportMemberRequestRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminImportMemberRequestRequest {
  if (json == null) {
    return json;
  }
  return {
    shoppingCartOrder: json["shopping_cart_order"],
    shoppingCartWaitingList: json["shopping_cart_waiting_list"],
    personalData: AdminImportMemberPersonalDataRequestFromJSON(
      json["personal_data"],
    ),
    sepaAllowed: json["sepa_allowed"],
    contractAccepted: json["contract_accepted"],
    statuteAccepted: json["statute_accepted"],
    pickupLocationIds: json["pickup_location_ids"],
    studentStatusEnabled: json["student_status_enabled"],
    paymentRhythm: json["payment_rhythm"],
    becomeMemberNow: json["become_member_now"],
    privacyPolicyRead: json["privacy_policy_read"],
    cancellationPolicyRead: json["cancellation_policy_read"],
    growingPeriodId: json["growing_period_id"],
    solidarityContribution: json["solidarity_contribution"],
    distributionChannels: json["distribution_channels"],
    feedback: json["feedback"] == null ? undefined : json["feedback"],
    associationMembershipTypeId:
      json["association_membership_type_id"] == null
        ? undefined
        : json["association_membership_type_id"],
    keycloakLookup:
      json["keycloak_lookup"] == null ? undefined : json["keycloak_lookup"],
    dateJoined:
      json["date_joined"] == null ? undefined : new Date(json["date_joined"]),
    privacyConsent:
      json["privacy_consent"] == null
        ? undefined
        : new Date(json["privacy_consent"]),
    memberNo: json["member_no"] == null ? undefined : json["member_no"],
  };
}

export function AdminImportMemberRequestRequestToJSON(
  json: any,
): AdminImportMemberRequestRequest {
  return AdminImportMemberRequestRequestToJSONTyped(json, false);
}

export function AdminImportMemberRequestRequestToJSONTyped(
  value?: AdminImportMemberRequestRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    shopping_cart_order: value["shoppingCartOrder"],
    shopping_cart_waiting_list: value["shoppingCartWaitingList"],
    personal_data: AdminImportMemberPersonalDataRequestToJSON(
      value["personalData"],
    ),
    sepa_allowed: value["sepaAllowed"],
    contract_accepted: value["contractAccepted"],
    statute_accepted: value["statuteAccepted"],
    pickup_location_ids: value["pickupLocationIds"],
    student_status_enabled: value["studentStatusEnabled"],
    payment_rhythm: value["paymentRhythm"],
    become_member_now: value["becomeMemberNow"],
    privacy_policy_read: value["privacyPolicyRead"],
    cancellation_policy_read: value["cancellationPolicyRead"],
    growing_period_id: value["growingPeriodId"],
    solidarity_contribution: value["solidarityContribution"],
    distribution_channels: value["distributionChannels"],
    feedback: value["feedback"],
    association_membership_type_id: value["associationMembershipTypeId"],
    keycloak_lookup: value["keycloakLookup"],
    date_joined:
      value["dateJoined"] == null
        ? undefined
        : (value["dateJoined"] as any).toISOString(),
    privacy_consent:
      value["privacyConsent"] == null
        ? undefined
        : (value["privacyConsent"] as any).toISOString(),
    member_no: value["memberNo"],
  };
}
