/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Mirrors BestellWizardConfirmOrderRequestSerializer.PersonalDataSerializer
 * but skips the phone/email validators that block imports for legacy data.
 *
 * email and phone_number are intentionally plain CharField (no EmailField,
 * no phonenumbers check) so admins can fix bad data via Django admin later.
 * @export
 * @interface AdminImportMemberPersonalDataRequest
 */
export interface AdminImportMemberPersonalDataRequest {
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  lastName: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  phoneNumber: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  street: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  street2: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  postcode: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  city: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  country: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  accountOwner: string;
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberPersonalDataRequest
   */
  iban: string;
}

/**
 * Check if a given object implements the AdminImportMemberPersonalDataRequest interface.
 */
export function instanceOfAdminImportMemberPersonalDataRequest(
  value: object,
): value is AdminImportMemberPersonalDataRequest {
  if (!("firstName" in value) || value["firstName"] === undefined) return false;
  if (!("lastName" in value) || value["lastName"] === undefined) return false;
  if (!("email" in value) || value["email"] === undefined) return false;
  if (!("phoneNumber" in value) || value["phoneNumber"] === undefined)
    return false;
  if (!("street" in value) || value["street"] === undefined) return false;
  if (!("street2" in value) || value["street2"] === undefined) return false;
  if (!("postcode" in value) || value["postcode"] === undefined) return false;
  if (!("city" in value) || value["city"] === undefined) return false;
  if (!("country" in value) || value["country"] === undefined) return false;
  if (!("accountOwner" in value) || value["accountOwner"] === undefined)
    return false;
  if (!("iban" in value) || value["iban"] === undefined) return false;
  return true;
}

export function AdminImportMemberPersonalDataRequestFromJSON(
  json: any,
): AdminImportMemberPersonalDataRequest {
  return AdminImportMemberPersonalDataRequestFromJSONTyped(json, false);
}

export function AdminImportMemberPersonalDataRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminImportMemberPersonalDataRequest {
  if (json == null) {
    return json;
  }
  return {
    firstName: json["first_name"],
    lastName: json["last_name"],
    email: json["email"],
    phoneNumber: json["phone_number"],
    street: json["street"],
    street2: json["street_2"],
    postcode: json["postcode"],
    city: json["city"],
    country: json["country"],
    accountOwner: json["account_owner"],
    iban: json["iban"],
  };
}

export function AdminImportMemberPersonalDataRequestToJSON(
  json: any,
): AdminImportMemberPersonalDataRequest {
  return AdminImportMemberPersonalDataRequestToJSONTyped(json, false);
}

export function AdminImportMemberPersonalDataRequestToJSONTyped(
  value?: AdminImportMemberPersonalDataRequest | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    first_name: value["firstName"],
    last_name: value["lastName"],
    email: value["email"],
    phone_number: value["phoneNumber"],
    street: value["street"],
    street_2: value["street2"],
    postcode: value["postcode"],
    city: value["city"],
    country: value["country"],
    account_owner: value["accountOwner"],
    iban: value["iban"],
  };
}
