/* tslint:disable */
/* eslint-disable */
/**
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AdminImportMemberResponse
 */
export interface AdminImportMemberResponse {
  /**
   *
   * @type {string}
   * @memberof AdminImportMemberResponse
   */
  memberId: string;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberResponse
   */
  wasExisting: boolean;
  /**
   *
   * @type {boolean}
   * @memberof AdminImportMemberResponse
   */
  orderImported: boolean;
}

/**
 * Check if a given object implements the AdminImportMemberResponse interface.
 */
export function instanceOfAdminImportMemberResponse(
  value: object,
): value is AdminImportMemberResponse {
  if (!("memberId" in value) || value["memberId"] === undefined) return false;
  if (!("wasExisting" in value) || value["wasExisting"] === undefined)
    return false;
  if (!("orderImported" in value) || value["orderImported"] === undefined)
    return false;
  return true;
}

export function AdminImportMemberResponseFromJSON(
  json: any,
): AdminImportMemberResponse {
  return AdminImportMemberResponseFromJSONTyped(json, false);
}

export function AdminImportMemberResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AdminImportMemberResponse {
  if (json == null) {
    return json;
  }
  return {
    memberId: json["member_id"],
    wasExisting: json["was_existing"],
    orderImported: json["order_imported"],
  };
}

export function AdminImportMemberResponseToJSON(
  json: any,
): AdminImportMemberResponse {
  return AdminImportMemberResponseToJSONTyped(json, false);
}

export function AdminImportMemberResponseToJSONTyped(
  value?: AdminImportMemberResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    member_id: value["memberId"],
    was_existing: value["wasExisting"],
    order_imported: value["orderImported"],
  };
}
